// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// WEB CONFIG
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDNW6p4TLdGoL-xz1TvBLdGgLOpnA6EQ6Y",
    authDomain: "social-stream-e9297.firebaseapp.com",
    projectId: "social-stream-e9297",
    storageBucket: "social-stream-e9297.appspot.com",
    messagingSenderId: "568190135670",
    appId: "1:568190135670:web:be315b005b61f52fc5de57",
    measurementId: "G-P5PS1LZZYV",
  );

  /// ANDROID CONFIG
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSasZFpiWlPZUz4oUmbPNC9m9dxP3c140',
    appId: '1:568190135670:android:1c40913c73738d1fc5de57',
    messagingSenderId: '568190135670',
    projectId: 'social-stream-e9297',
    storageBucket: 'social-stream-e9297.appspot.com',
  );

  /// IOS CONFIG
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNW6p4TLdGoL-xz1TvBLdGgLOpnA6EQ6Y',
    appId: '1:568190135670:ios:be315b005b61f52fc5de57',
    messagingSenderId: '568190135670',
    projectId: 'social-stream-e9297',
    storageBucket: 'social-stream-e9297.appspot.com',
    iosBundleId: 'com.hafeeimran.socialStream',
  );

  /// MACOS CONFIG
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNW6p4TLdGoL-xz1TvBLdGgLOpnA6EQ6Y',
    appId: '1:568190135670:ios:be315b005b61f52fc5de57',
    messagingSenderId: '568190135670',
    projectId: 'social-stream-e9297',
    storageBucket: 'social-stream-e9297.appspot.com',
    iosBundleId: 'com.hafeeimran.socialStream',
  );

  /// WINDOWS CONFIG
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNW6p4TLdGoL-xz1TvBLdGgLOpnA6EQ6Y',
    appId: '1:568190135670:web:be315b005b61f52fc5de57',
    messagingSenderId: '568190135670',
    projectId: 'social-stream-e9297',
    authDomain: 'social-stream-e9297.firebaseapp.com',
    storageBucket: 'social-stream-e9297.appspot.com',
    measurementId: 'G-P5PS1LZZYV',
  );
}
